### ISSUE TITLE
AbstractEditableModelScope.removeValue doesn't remove values

### ISSUE THREAD

**Issue by pdulth** [eclipse/org.eclipse.emf.diffmerge.core#235]
removeValue("value") shall work even if the "value" is not strictly == to the value.

**Comment by oconstant** [comment]
Dang, yes. equals(Object) should be used for attribute values while == is more appropriate for reference values.

When the feature is many-valued it is automatically the case: EDataTypeEList (for attributes) has useEquals() == true while EObjectEList (for references) has useEquals() == false.

Given how the JVM manages data values, the issue applies to certain values of single-valued attribute of certain datatypes.
Plenty of values are concerned by the issue but I would say the most common attribute values in typical (non-scientific, non-data science-oriented) engineering models tend to be among those that are not. That might explain why the issue was not caught earlier or detected by tests.

Typically, testing with jshell in OpenJDK 14:
Obviously MyEnum.LITERAL1 == MyEnum.LITERAL1  ==> true
'c' == 'c'  ==> true
"hello" == "hello"  ==> true
Boolean.valueOf(true) == Boolean.valueOf(true)  ==> true
Integer.valueOf(127) == Integer.valueOf(127)  ==> true
Long.valueOf(127l) == Long.valueOf(127l)  ==> true

Whereas:
Integer.valueOf(128) == Integer.valueOf(128)  ==> false
Long.valueOf(128l) == Long.valueOf(128l)  ==> false
Float.valueOf(3.14f) == Float.valueOf(3.14f)  ==> false
Double.valueOf(3.14) == Double.valueOf(3.14)  ==> false

**Comment by pdulth** [comment]
Ah yes you right, will do check on EAttribute
